title: Pitago
description: Pitago is a mobile app that teaches math through interactive, gamified learning.
theme: just-the-docs

# Your site URL (update if deploying to a custom domain)
url: https://NeriDavid1.github.io

# Optional: Repository link in the top right corner
aux_links:
  View the Source on GitHub: https://github.com/NeriDavid1/pitago-docs

# Enable search
search_enabled: true

# Customize the logo if available
logo: "/assets/images/Icon.png"

# Customize the site navigation order if needed
nav_sort: case_insensitive

# Enable or disable callouts (e.g., {: .note })
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow

# Optional: Google Analytics (replace with your ID if needed)
# ga_tracking: UA-XXXXXXXXX-X

# If using a favicon
# favicon_ico: "/assets/images/favicon.ico"
